<br>
<font size="+2"> In this notebook, we will be working on questions in Colab Notebooks section in Module 1. </font>
<br><br>

In this notebook, we will continue working with `city_temperature.csv` datafile; remember that the format of this datafile is the same as the temperature datafile we were using in the video, it just has many more data points because it includes temperature data for the entire world (i.e. rows).

<font color='#FF4500' size="+2"> To set up your DataFrame for these questions, run the cell below. </font>

In [ ]:
from google.colab import drive
drive.mount('/content/drive/', force_remount=True)

import os
os.chdir("/content/drive/My Drive/AIMOOC")

import pandas as pd
df2 = pd.read_csv("/content/drive/My Drive/AIMOOC/Modules/Module1/Data/city_temperature.csv")

# Questions on Visualizations

In this series of questions you will be deciding which datasets match each plot. Create the following cleaned up dataset called `clean`, which is the full temperature dataset without any -99 temperatures. Use the command below (run the cell below), assuming that your full dataset is saved in a DataFrame called df2.

In [ ]:
clean = df2.loc[(df2["AvgTemperature"] != -99)]

## Question 1

Create an x-y plot of the average temperature in Paris in the year 2002.

In [ ]:
# Your code here

## Question 2

Create a scatter plot of the average temperature in Tokyo in the year 1996.

In [ ]:
# Your code here

## Question 3

Create a histogram of the average temperature in the country Sweden in March with 10 bins.

In [ ]:
# Your code here

## Question 4

Create a histogram of the average temperature in the country Sweden in March with 4 bins. Use the histogram to approximate the total number of data points.

In [ ]:
# Your code here

## Question 5

What is the correlation between average temperature and month for the country Japan in the year 2000 and months January through July?

In [ ]:
# Your codde here

## Question 6

What is the correlation between average temperature and month for the country Argentina in the year 2000 and months January through July?

In [ ]:
# Your code here

## Question 7

What is the correlation between average temperature and month for the country Colombia in the year 2000? Round to 2 decimal places.

In [ ]:
# Your code here